config/routes.rb
Rails.application.routes.draw do
  resources :clients, only: [:index, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
  end

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/index.html.erb
<h2>Clients</h2>

<%= link_to "Add new client", new_client_path %>

app/views/clients/new.html.erb
<h2>Add a new client</h2>

<%= form_for(Client.new) do |f| %>
  <%= f.label :company_name %>
  <%= f.text_field :company_name %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :contact_first_name %>
  <%= f.text_field :contact_first_name %>
  <%= f.label :contact_last_name %>
  <%= f.text_field :contact_last_name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :address_1 %>
  <%= f.text_field :address_1 %>
  <%= f.label :address_2 %>
  <%= f.text_field :address_2 %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :postal_code %>
  <%= f.text_field :postal_code %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quicktrack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1"></head>

  <body>
    <%= yield %>
  </body>
</html>